aicp: changelog: Only rebuild changelog when needed, and cleanup
If we have built the changelog on a prior build and it is still up to
date, skip building the changelog again.

In order to detect whether the changelog is up to date, we write a
revisioned manifest.  If the manifest exists (from a prior run), it is
not newer than the changelog, and it matches the current repo state,
then the changelog is up to date and we don't need to do anything.

When we do need to write a changelog, we remove the old manifest, write
the changelog, then update the manifest.  This ensures that if any repo
command fails, the manifest will not exist and the changelog will be
written again on the next run.

Also do some cleanup:
 * Use 'set -e' to detect failure in repo commands.
 * Write changelog to $OUT, not the build topdir.
 * Exit early when USER_BUILD_NO_CHANGELOG is set.
 * Use quotes around variable references.
 * Make all local shell variables lower case.
 * Do not export variables needlessly.

Finally note that most or all of this could have been done in directly
in the core build system as make rules.  But let's leave that change
for another time.

Change-Id: Ib390007cda3f8148e96ceeca23db97bde3fcc15c

diff --git a/tools/changelog b/tools/changelog
--- a/tools/changelog
+++ b/tools/changelog
@@ -1,57 +1,68 @@
 #!/bin/sh
-#
-# Exports
-dir=$ANDROID_BUILD_TOP
-out=$dir/out/target/product
 
-export Changelog=Changelog.txt
+set -e
 
-if [ -f $Changelog ];
-then
-	rm -f $Changelog
+# Store the main manifest and changelog in $OUT.
+# Copy the main manifest to the target system/etc.
+manifest="$OUT/manifest.xml"
+changelog="$OUT/Changelog.txt"
+system_changelog="$OUT/system/etc/Changelog.txt"
+
+# Use 'export USER_BUILD_NO_CHANGELOG=1' before build/envsetup.sh to skip changelog
+if [ "$USER_BUILD_NO_CHANGELOG" = "1" ]; then
+  echo "Skipped because variable 'USER_BUILD_NO_CHANGELOG' was set to 1" | tee "$changelog"
+  exit 0
 fi
 
-touch $Changelog
+repo manifest -r > "$manifest.tmp"
+if [ -f "$manifest" -a ! "$manifest" -nt "$changelog" ]; then
+  diff=0
+  cmp "$manifest" "$manifest.tmp" >/dev/null 2>&1 || diff=1
+  if [ $diff -eq 0 ]; then
+    # The changelog is up to date.
+    # Cleanup and copy it over to system.
+    echo ${buildppl}"Changelog up to date"${txtrst}
+    rm -f "$manifest.tmp"
+    mkdir -p $(dirname "$system_changelog")
+    cp "$changelog" "$system_changelog"
+    exit 0
+  fi
+fi
 
 # Print something to build output
 echo ${bldppl}"Generating changelog..."${txtrst}
 
-# Use 'export USER_BUILD_NO_CHANGELOG=1' before build/envsetup.sh to skip changelog
-if [ $USER_BUILD_NO_CHANGELOG ]&&[ "$USER_BUILD_NO_CHANGELOG" -eq 1 ]; then
-  echo "Skipped because variable 'USER_BUILD_NO_CHANGELOG' was set to 1" | tee $Changelog;
-else
-  for i in $(seq 10);
-  do
-  export After_Date=`date --date="$i days ago" +%m-%d-%Y`
-  k=$(expr $i - 1)
-    export Until_Date=`date --date="$k days ago" +%m-%d-%Y`
+# Delete the existing manifest so that if we fail, the next build
+# will not think it is up to date.
+rm -f "$manifest"
 
-    # Line with after --- until was too long for a small ListView
-    echo '====================' >> $Changelog;
-    echo  "     "$Until_Date       >> $Changelog;
-    echo '===================='	>> $Changelog;
-    echo >> $Changelog;
+rm -f "$changelog"
+touch "$changelog"
+for i in $(seq 1 10);
+do
+  after_date=`date --date="$i days ago" +%m-%d-%Y`
+  k=$((i - 1))
+  until_date=`date --date="$k days ago" +%m-%d-%Y`
 
-    # Cycle through every repo to find commits between 2 dates
-    CURRENT_PATH="$(realpath `pwd`)"
+  # Line with after --- until was too long for a small ListView
+  echo "====================" >> "$changelog"
+  echo "     $until_date"     >> "$changelog"
+  echo "====================" >> "$changelog"
+  echo >> "$changelog"
 
-    repo forall -c "GIT_LOG=\`git log --oneline --after=$After_Date --until=$Until_Date\` ; if [ ! -z \"\$GIT_LOG\" ]; then printf  '\n   * '; realpath \`pwd\` | sed 's|^$CURRENT_PATH/||' ; echo \"\$GIT_LOG\"; fi" >> $Changelog
-    echo >> $Changelog;
-  done
+  # Cycle through every repo to find commits between 2 dates
+  current_path="$(realpath `pwd`)"
 
-  sed -i 's/project/   */g' $Changelog
-fi
+  repo forall -c "GIT_LOG=\`git log --oneline --after=$after_date --until=$until_date\` ; if [ ! -z \"\$GIT_LOG\" ]; then printf  '\n   * '; realpath \`pwd\` | sed 's|^$current_path/||' ; echo \"\$GIT_LOG\"; fi" >> "$changelog"
+  echo >> "$changelog"
+done
 
-if [ -e $out/*/$Changelog ]
-then
-rm $out/*/$Changelog
-fi
-if [ -e $out/*/system/etc/$Changelog ]
-then
-rm $out/*/system/etc/$Changelog
-fi
-cp $Changelog $OUT/system/etc/
-cp $Changelog $OUT/
-rm $Changelog
+sed -i 's/^project/   */g' "$changelog"
+
+# Now that we have successfully generated the changelog, move the
+# manifest into position and copy the changelog to the target.
+mv "$manifest.tmp" "$manifest"
+mkdir -p $(dirname "$system_changelog")
+cp "$changelog" "$system_changelog"
 
 exit 0
